/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uy.bios.dgg.bibliotecamistica.presentacion;

import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import uy.bios.dgg.bibliotecamistica.excepciones.AutorException;
import uy.bios.dgg.bibliotecamistica.logica.Autor;
import uy.bios.dgg.bibliotecamistica.logica.Autores;
import uy.bios.dgg.bibliotecamistica.logica.FachadaLogica;

/**
 *
 * @author DGG
 */
public class VentanaAutores extends JFrame {

    private final int MAX_LARGO_TEXTO = 45;
    private final JFrame ventanaAnterior;
    private JComboBox combo;
    private final FachadaLogica fachadaLogica = new FachadaLogica();
    private Autor autor = new Autor();

    /**
     * Creates new form VentanaSocios
     *
     * @param ventana
     */
    public VentanaAutores(JFrame ventana) {
        initComponents();
        ventanaAnterior = ventana;
        limpiarFormulario();
    }
    
    public VentanaAutores(JFrame ventana, JComboBox combo) {
        initComponents();
        ventanaAnterior = ventana;
        this.combo = combo;
        limpiarFormulario();
    }
    
    private void volver() {
        if (this.ventanaAnterior.getName().equals("frameLibros")){
            refrescaCombo();
        }
        ventanaAnterior.setVisible(true);
        this.dispose();
    }

    public void setYmostrarAutor(Autor autor) {
        this.autor = autor;
        mostrarAutor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jTxtNombre = new javax.swing.JTextField();
        jTxtApellido = new javax.swing.JTextField();
        jTxtNacionalidad = new javax.swing.JTextField();
        jBtnBuscar = new javax.swing.JButton();
        jBtnVolver = new javax.swing.JToggleButton();
        jBtnNuevo = new javax.swing.JButton();
        jBtnAceptar = new javax.swing.JButton();
        jBtnBorrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jBtnVerTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Autores");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Código:");

        jLabel3.setText("Nombre:");

        jLabel5.setText("Apellido:");

        jLabel6.setText("Nacionalidad:");

        jTxtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCodigoKeyTyped(evt);
            }
        });

        jTxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNombreKeyTyped(evt);
            }
        });

        jTxtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtApellidoKeyTyped(evt);
            }
        });

        jTxtNacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNacionalidadKeyTyped(evt);
            }
        });

        jBtnBuscar.setText("Buscar");
        jBtnBuscar.setToolTipText("Busca el socio por el documento ingresado");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtApellido)
                    .addComponent(jTxtNacionalidad)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTxtNombre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnVolver.setText("Volver");
        jBtnVolver.setToolTipText("Vuelve al menú principal");
        jBtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVolverActionPerformed(evt);
            }
        });

        jBtnNuevo.setText("Nuevo");
        jBtnNuevo.setToolTipText("Limpia la panatalla para un nuevo socio.");
        jBtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoActionPerformed(evt);
            }
        });

        jBtnAceptar.setText("Aceptar");
        jBtnAceptar.setToolTipText("Actualiza el socio actual o inserta uno nuevo.");
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });

        jBtnBorrar.setText("Borrar");
        jBtnBorrar.setToolTipText("Borra el socio.");
        jBtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBorrarActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/bios/dgg/bibliotecamistica/imagenes/iconsUsuarioMaquina48.png"))); // NOI18N
        jLabel9.setText(" Altas, bajas y modificaciones de autores.");

        jBtnVerTodos.setText("Ver todos");
        jBtnVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVerTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnVerTodos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnVerTodos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNuevo)
                    .addComponent(jBtnAceptar)
                    .addComponent(jBtnBorrar)
                    .addComponent(jBtnVolver))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCodigoKeyTyped
        //Controlamos que no supere el largo del campo de la BD
        if (jTxtCodigo.getText().length() == MAX_LARGO_TEXTO)
            evt.consume();
    }//GEN-LAST:event_jTxtCodigoKeyTyped

    private void jTxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNombreKeyTyped
        //Controlamos que no supere el largo del campo de la BD
        if (jTxtNombre.getText().length() == MAX_LARGO_TEXTO)
            evt.consume();
    }//GEN-LAST:event_jTxtNombreKeyTyped

    private void jTxtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtApellidoKeyTyped
        //Controlamos que no supere el largo del campo de la BD
        if (jTxtApellido.getText().length() == MAX_LARGO_TEXTO)
            evt.consume();
    }//GEN-LAST:event_jTxtApellidoKeyTyped

    private void jTxtNacionalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNacionalidadKeyTyped
        //Controlamos que no supere el largo del campo de la BD
        if (jTxtNacionalidad.getText().length() == MAX_LARGO_TEXTO)
            evt.consume();
    }//GEN-LAST:event_jTxtNacionalidadKeyTyped

    private void jBtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVolverActionPerformed
        this.volver();
    }//GEN-LAST:event_jBtnVolverActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //this.volver();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.volver();
    }//GEN-LAST:event_formWindowClosing

    private void jBtnVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerTodosActionPerformed
        VentanaAutoresVerTodos ventana = new VentanaAutoresVerTodos(this); //Creo ventanaCategorias y le paso el menu como parametro para poder volver al menu
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnVerTodosActionPerformed

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
        if (!this.jTxtCodigo.getText().trim().equals("")) {
            try {
                String codigo = this.jTxtCodigo.getText().trim();
                autor = fachadaLogica.obtenerAutor(codigo);
                if (autor.getIdautor() == null) {
                    JOptionPane.showMessageDialog(null, "No se encontró un autor con el código ingresado.", "Resultado de la búsqueda", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    mostrarAutor();
                }
            } catch (AutorException ex) {
                JOptionPane.showMessageDialog(null, ex, "Atención", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private void jBtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBorrarActionPerformed
        if (checkAptoBorrar()) {
            try {
                if (JOptionPane.showConfirmDialog(null, "¿Confirma el borrado del autor " + autor + "?", "Atención", JOptionPane.YES_NO_OPTION) == 0) {
                    fachadaLogica.borrarAutor(autor);
                    this.limpiarFormulario();
                    JOptionPane.showMessageDialog(null, "El autor " + autor + " se borró correctamente.", "Baja de autor", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (AutorException ex) {
                JOptionPane.showMessageDialog(null, ex, "Atención", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo borrar ningún autor. \n Por favor seleccione uno y vuelva a intentarlo.", "Baja de autor", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBtnBorrarActionPerformed

    private void jBtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoActionPerformed
        limpiarFormulario();
        this.autor = new Autor();
    }//GEN-LAST:event_jBtnNuevoActionPerformed

    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
        //atención debemos chequear que no existe el código para no repetirlo
        if (checkAptoModificar()) {
            cargaDatosDesdeFormulario();
            try {
                if (JOptionPane.showConfirmDialog(null, "¿Confirma la modificación del autor " + autor + "?", "Atención", JOptionPane.YES_NO_OPTION) == 0) {
                    fachadaLogica.modificarAutor(autor);
                    JOptionPane.showMessageDialog(null, "La modificación se realizó correctamente.", "Autores", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (AutorException ex) {
                JOptionPane.showMessageDialog(null, "Atención: \n" + ex, "Autores", JOptionPane.WARNING_MESSAGE);
            }
        } else if (checkAptoIngresar()) {
            cargaDatosDesdeFormulario();
            try {
                fachadaLogica.ingresarAutor(autor);
                JOptionPane.showMessageDialog(null, "El alta se realizó correctamente.", "Autores", JOptionPane.INFORMATION_MESSAGE);
            } catch (AutorException ex) {
                JOptionPane.showMessageDialog(null, "Atención: \n" + ex, "Autores", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo realizar ninguna tarea con autores. \n Por favor seleccione uno para su modificación o clic en limpiar para ingresar uno nuevo.", "Autores", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBtnAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JButton jBtnBorrar;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JButton jBtnVerTodos;
    private javax.swing.JToggleButton jBtnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtNacionalidad;
    private javax.swing.JTextField jTxtNombre;
    // End of variables declaration//GEN-END:variables

    private void limpiarFormulario() {
        this.jTxtCodigo.setText("");
        this.jTxtNombre.setText("");
        this.jTxtApellido.setText("");
        this.jTxtNacionalidad.setText("");
    }

    private void mostrarAutor() {
        this.jTxtCodigo.setText(autor.getCodigo());
        this.jTxtNombre.setText(autor.getNombre());
        this.jTxtApellido.setText(autor.getApellido());
        this.jTxtNacionalidad.setText(autor.getNacionalidad());
    }

    private void cargaDatosDesdeFormulario() {
        autor.setCodigo(this.jTxtCodigo.getText());
        autor.setNombre(this.jTxtNombre.getText());
        autor.setApellido(this.jTxtApellido.getText());
        autor.setNacionalidad(this.jTxtNacionalidad.getText());
    }

    private boolean checkAptoBorrar() {
        //chequeo para asegurarnos que la categoria en memoria sea igual a la que se visualiza en pantalla
        if (autor.getIdautor() != null) {
            if (this.jTxtCodigo.getText().trim().equals(autor.getCodigo())) {
                return true;
            }
        }
        return false;
    }

    private boolean checkAptoModificar() {
        //chequeo para saber si es apto para realizar una modificación
        if (autor.getIdautor() != null) {
            if (!this.jTxtCodigo.getText().trim().equals(autor.getCodigo()) || !this.jTxtNombre.getText().trim().equals(autor.getNombre()) || !this.jTxtApellido.getText().trim().equals(autor.getApellido()) || !this.jTxtNacionalidad.getText().trim().equals(autor.getNacionalidad())) {
                if (!this.jTxtCodigo.getText().trim().equals("") && !this.jTxtNombre.getText().trim().equals("") && !this.jTxtApellido.getText().trim().equals("") && !this.jTxtNacionalidad.getText().trim().equals("")) {
                    return true;
                }
            }
        }
        return false;
    }

    private boolean checkAptoIngresar() {
        //chequeo para saber si es apto para realizar un nuevo ingreso
        if (autor.getIdautor() == null) {
            if (!this.jTxtCodigo.getText().trim().equals("") && !this.jTxtNombre.getText().trim().equals("") && !this.jTxtApellido.getText().trim().equals("") && !this.jTxtNacionalidad.getText().trim().equals("")) {
                return true;
            }
        }
        return false;
    }

    private void refrescaCombo() {
        Autores autores;
        this.combo.removeAllItems();
        try {
            autores = fachadaLogica.obtenerAutores();
            for (int i = 0; i < autores.getAutores().size(); i++) {
                this.combo.addItem(autores.getAutores().get(i));
                if (autores.getAutores().get(i).getIdautor().equals(this.autor.getIdautor())){ //si es el autor actual lo selecciono
                    this.combo.setSelectedIndex(i);
                }
            }
        } catch (AutorException ex) {
            JOptionPane.showMessageDialog(null, "Atención: \n" + ex, "Libros", JOptionPane.WARNING_MESSAGE);
        }
    }
}
