/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uy.bios.dgg.bibliotecamistica.presentacion;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import uy.bios.dgg.bibliotecamistica.excepciones.SocioException;
import uy.bios.dgg.bibliotecamistica.logica.FachadaLogica;
import uy.bios.dgg.bibliotecamistica.logica.Socio;

/**
 *
 * @author Green
 */
public class VentanaSocios extends JFrame {

    private final int MAX_LARGO_TEXTO = 45;
    private final JFrame ventanaAnterior;
    private Socio socio = new Socio();
    private final FachadaLogica fachadaLogica = new FachadaLogica();
    

    /**
     * Creates new form VentanaSocios
     *
     * @param ventana
     */
    public VentanaSocios(JFrame ventana) {
        ventanaAnterior = ventana;
        initComponents();
    }

    private void volver() {
        ventanaAnterior.setVisible(true);
        this.dispose();
    }
    public void setYmostrarSocio(Socio socio) {
        this.socio = socio;
        mostrarSocio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtDocumento = new javax.swing.JTextField();
        jTxtNombre = new javax.swing.JTextField();
        jTxtApellido = new javax.swing.JTextField();
        jTxtNacionalidad = new javax.swing.JTextField();
        jTxtDireccion = new javax.swing.JTextField();
        jTxtTelefono = new javax.swing.JTextField();
        jTxtEmail = new javax.swing.JTextField();
        jBtnBuscar = new javax.swing.JButton();
        jBtnVolver = new javax.swing.JToggleButton();
        jBtnLimpiar = new javax.swing.JButton();
        jBtnAceptar = new javax.swing.JButton();
        jBtnBorrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jBtnVerTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Socios");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Documento de Identidad:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("E-mail:");

        jLabel5.setText("Apellido:");

        jLabel6.setText("Nacionalidad:");

        jLabel7.setText("Dirección:");

        jLabel8.setText("Teléfono:");

        jTxtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtDocumentoKeyTyped(evt);
            }
        });

        jTxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNombreKeyTyped(evt);
            }
        });

        jTxtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtApellidoKeyTyped(evt);
            }
        });

        jTxtNacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNacionalidadKeyTyped(evt);
            }
        });

        jTxtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtDireccionKeyTyped(evt);
            }
        });

        jTxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtTelefonoKeyTyped(evt);
            }
        });

        jTxtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtEmailKeyTyped(evt);
            }
        });

        jBtnBuscar.setText("Buscar");
        jBtnBuscar.setToolTipText("Busca el socio por el documento ingresado");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtNombre)
                    .addComponent(jTxtApellido)
                    .addComponent(jTxtNacionalidad)
                    .addComponent(jTxtDireccion)
                    .addComponent(jTxtTelefono)
                    .addComponent(jTxtEmail)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnVolver.setText("Volver");
        jBtnVolver.setToolTipText("Vuelve al menú principal");
        jBtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVolverActionPerformed(evt);
            }
        });

        jBtnLimpiar.setText("Limpiar");
        jBtnLimpiar.setToolTipText("Limpia la panatalla para un nuevo socio.");
        jBtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarActionPerformed(evt);
            }
        });

        jBtnAceptar.setText("Aceptar");
        jBtnAceptar.setToolTipText("Actualiza el socio actual o inserta uno nuevo.");
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });

        jBtnBorrar.setText("Borrar");
        jBtnBorrar.setToolTipText("Borra el socio.");
        jBtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBorrarActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/bios/dgg/bibliotecamistica/imagenes/iconsUsuario40.png"))); // NOI18N
        jLabel9.setText(" Altas, bajas y modificaciones de socios.");

        jBtnVerTodos.setText("Ver todos");
        jBtnVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVerTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnVerTodos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnVerTodos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnLimpiar)
                    .addComponent(jBtnAceptar)
                    .addComponent(jBtnBorrar)
                    .addComponent(jBtnVolver))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDocumentoKeyTyped
        //Controlamos que no supere el largo del campo de la BD
        if (jTxtDocumento.getText().length() == MAX_LARGO_TEXTO)
            evt.consume();
    }//GEN-LAST:event_jTxtDocumentoKeyTyped

    private void jTxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNombreKeyTyped
        //Controlamos que no supere el largo del campo de la BD
        if (jTxtNombre.getText().length() == MAX_LARGO_TEXTO)
            evt.consume();
    }//GEN-LAST:event_jTxtNombreKeyTyped

    private void jTxtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtApellidoKeyTyped
        //Controlamos que no supere el largo del campo de la BD
        if (jTxtApellido.getText().length() == MAX_LARGO_TEXTO)
            evt.consume();
    }//GEN-LAST:event_jTxtApellidoKeyTyped

    private void jTxtNacionalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNacionalidadKeyTyped
        //Controlamos que no supere el largo del campo de la BD
        if (jTxtNacionalidad.getText().length() == MAX_LARGO_TEXTO)
            evt.consume();
    }//GEN-LAST:event_jTxtNacionalidadKeyTyped

    private void jTxtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDireccionKeyTyped
        //Controlamos que no supere el largo del campo de la BD
        if (jTxtDireccion.getText().length() == MAX_LARGO_TEXTO)
            evt.consume();
    }//GEN-LAST:event_jTxtDireccionKeyTyped

    private void jTxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTelefonoKeyTyped
        //Controlamos que no supere el largo del campo de la BD
        if (jTxtTelefono.getText().length() == MAX_LARGO_TEXTO)
            evt.consume();
    }//GEN-LAST:event_jTxtTelefonoKeyTyped

    private void jTxtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtEmailKeyTyped
        //Controlamos que no supere el largo del campo de la BD
        if (jTxtEmail.getText().length() == MAX_LARGO_TEXTO)
            evt.consume();
    }//GEN-LAST:event_jTxtEmailKeyTyped

    private void jBtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVolverActionPerformed
        this.volver();
    }//GEN-LAST:event_jBtnVolverActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //this.volver();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.volver();
    }//GEN-LAST:event_formWindowClosing

    private void jBtnVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerTodosActionPerformed
        VentanaSociosVerTodos ventana = new VentanaSociosVerTodos(this); //Creo ventanaCategorias y le paso el menu como parametro para poder volver al menu
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnVerTodosActionPerformed

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
        
        if (!this.jTxtDocumento.getText().trim().equals("")) {
            try {
                String docIdentidad = this.jTxtDocumento.getText().trim();
                socio = fachadaLogica.obtenerSocio(docIdentidad);
                if (socio.getIdSocio() == null) {
                    JOptionPane.showMessageDialog(null, "No se encontró un socio con el Documento ingresado.", "Resultado de la búsqueda", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    mostrarSocio();
                }
            } catch (SocioException ex) {
                JOptionPane.showMessageDialog(null, ex, "Atención", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private void jBtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarActionPerformed
        
        limpiarFormulario();
        this.socio = new Socio();
    }//GEN-LAST:event_jBtnLimpiarActionPerformed

    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
       if (checkAptoModificar()) {
            cargaDatosDesdeFormulario();
            try {
                if (JOptionPane.showConfirmDialog(null, "¿Confirma la modificación del socio " + socio + "?", "Atención", JOptionPane.YES_NO_OPTION) == 0) {
                    fachadaLogica.modificarSocio(socio);
                    JOptionPane.showMessageDialog(null, "La modificación se realizó correctamente.", "Socios", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SocioException ex) {
                JOptionPane.showMessageDialog(null, "Atención: \n" + ex, "Socios", JOptionPane.WARNING_MESSAGE);
            }
        } else if (checkAptoIngresar()) {
            cargaDatosDesdeFormulario();
            try {
                fachadaLogica.ingresarSocio(socio);
                JOptionPane.showMessageDialog(null, "El alta se realizó correctamente.", "Socios", JOptionPane.INFORMATION_MESSAGE);
            } catch (SocioException ex) {
                JOptionPane.showMessageDialog(null, "Atención: \n" + ex, "Socios", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo realizar ninguna tarea con Socios. \n Por favor seleccione uno para su modificación o clic en limpiar para ingresar uno nuevo.", "Socios", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBtnAceptarActionPerformed

    private void jBtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBorrarActionPerformed
        if (checkAptoBorrar()) {
            try {
                if (JOptionPane.showConfirmDialog(null, "¿Confirma el borrado del socio " + socio + "?", "Atención", JOptionPane.YES_NO_OPTION) == 0) {
                    fachadaLogica.borrarSocio(socio);
                    this.limpiarFormulario();
                    JOptionPane.showMessageDialog(null, "El socio " + socio + " se borró correctamente.", "Baja de autor", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SocioException ex) {
                JOptionPane.showMessageDialog(null, ex, "Atención", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo borrar ningún socio. \n Por favor seleccione uno y vuelva a intentarlo.", "Baja de autor", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBtnBorrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JButton jBtnBorrar;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JButton jBtnVerTodos;
    private javax.swing.JToggleButton jBtnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JTextField jTxtDireccion;
    private javax.swing.JTextField jTxtDocumento;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtNacionalidad;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtTelefono;
    // End of variables declaration//GEN-END:variables

    private void limpiarFormulario() {
        this.jTxtDireccion.setText("");
        this.jTxtNombre.setText("");
        this.jTxtApellido.setText("");
        this.jTxtNacionalidad.setText("");
        this.jTxtDocumento.setText("");
        this.jTxtEmail.setText("");
        this.jTxtTelefono.setText("");
    }
    
    private void mostrarSocio() {
        
        this.jTxtNombre.setText(socio.getNombre());
        this.jTxtApellido.setText(socio.getApellido());
        this.jTxtNacionalidad.setText(socio.getNacionalidad());
        this.jTxtDireccion.setText(socio.getDireccion());
        this.jTxtDocumento.setText(socio.getDocIdentidad());
        this.jTxtEmail.setText(socio.getEmail());
        this.jTxtTelefono.setText(socio.getTelefono());
    }
private void cargaDatosDesdeFormulario() {
        socio.setDocIdentidad(this.jTxtDocumento.getText());
        socio.setNombre(this.jTxtNombre.getText());
        socio.setApellido(this.jTxtApellido.getText());
        socio.setNacionalidad(this.jTxtNacionalidad.getText());
        socio.setDireccion(this.jTxtDireccion.getText());
        socio.setTelefono(this.jTxtTelefono.getText());
        socio.setEmail(this.jTxtEmail.getText());
    }
private boolean checkAptoBorrar() {
        //chequeo para asegurarnos que la categoria en memoria sea igual a la que se visualiza en pantalla
        if (socio.getIdSocio() != null) {
            if (this.jTxtDocumento.getText().trim().equals(socio.getDocIdentidad())) {
                return true;
            }
        }
        return false;
    }
    private boolean checkAptoModificar() {
        //chequeo para saber si es apto para realizar una modificación
        if (socio.getIdSocio() != null) {
            if (!this.jTxtDocumento.getText().trim().equals(socio.getDocIdentidad()) || !this.jTxtNombre.getText().trim().equals(socio.getNombre()) || !this.jTxtApellido.getText().trim().equals(socio.getApellido()) || !this.jTxtNacionalidad.getText().trim().equals(socio.getNacionalidad()) || !this.jTxtDireccion.getText().trim().equals(socio.getDireccion()) || !this.jTxtTelefono.getText().trim().equals(socio.getTelefono()) || !this.jTxtEmail.getText().trim().equals(socio.getEmail())) {
                if (!this.jTxtDocumento.getText().trim().equals("") && !this.jTxtNombre.getText().trim().equals("") && !this.jTxtApellido.getText().trim().equals("") && !this.jTxtNacionalidad.getText().trim().equals("") && !this.jTxtDireccion.getText().trim().equals("") && !this.jTxtTelefono.getText().trim().equals("") && !this.jTxtEmail.getText().trim().equals("")) {
                    return true;
                }
            }
        }
        return false;
    }
    private boolean checkAptoIngresar() {
        //chequeo para saber si es apto para realizar un nuevo ingreso
        if (socio.getIdSocio() == null) {
            if (!this.jTxtDocumento.getText().trim().equals("") && !this.jTxtNombre.getText().trim().equals("") && !this.jTxtApellido.getText().trim().equals("") && !this.jTxtNacionalidad.getText().trim().equals("") && !this.jTxtDireccion.getText().trim().equals("") && !this.jTxtTelefono.getText().trim().equals("") && !this.jTxtEmail.getText().trim().equals("")) {
                    return true;
            }
        }
        return false;
    }



}
