/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uy.bios.dgg.bibliotecamistica.presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author dasm2
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenu
     */
    public VentanaMenu() {
        initComponents();
    }
    
    public void salir(){
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Confirma salir?", "Atención", JOptionPane.YES_NO_OPTION);
        if (respuesta == 0) {
            this.dispose();
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBtnSocios = new javax.swing.JButton();
        jBtnAutores = new javax.swing.JButton();
        jBtnCategorias = new javax.swing.JButton();
        jBtnLibros = new javax.swing.JButton();
        jBtnPrestamos = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLblAyuda = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menú Principal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Biblioteca Mística");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jBtnSocios.setText("Socios");
        jBtnSocios.setToolTipText("Altas, bajas y modificaciones de socios.");
        jBtnSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnSociosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSociosMouseExited(evt);
            }
        });
        jBtnSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSociosActionPerformed(evt);
            }
        });

        jBtnAutores.setText("Autores");
        jBtnAutores.setToolTipText("Altas, bajas y modificaciones de autores.");
        jBtnAutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnAutoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnAutoresMouseExited(evt);
            }
        });
        jBtnAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAutoresActionPerformed(evt);
            }
        });

        jBtnCategorias.setText("Categorías");
        jBtnCategorias.setToolTipText("Altas, bajas y modificaciones de categorias.");
        jBtnCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnCategoriasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnCategoriasMouseExited(evt);
            }
        });
        jBtnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCategoriasActionPerformed(evt);
            }
        });

        jBtnLibros.setText("Libros");
        jBtnLibros.setToolTipText("Altas, bajas y modificaciones de libros.");
        jBtnLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLibrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLibrosMouseExited(evt);
            }
        });
        jBtnLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLibrosActionPerformed(evt);
            }
        });

        jBtnPrestamos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnPrestamos.setText("Préstamos");
        jBtnPrestamos.setToolTipText("Préstamos, devoluciones y listados.");
        jBtnPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnPrestamosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnPrestamosMouseExited(evt);
            }
        });

        jBtnSalir.setText("Salir");
        jBtnSalir.setToolTipText("Sale del programa.");
        jBtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSalirMouseExited(evt);
            }
        });
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnSocios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jBtnPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jBtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnSocios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAutores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnCategorias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnLibros)
                .addGap(37, 37, 37)
                .addComponent(jBtnPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnSalir)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setPreferredSize(new java.awt.Dimension(254, 258));

        jLblAyuda.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLblAyuda.setForeground(new java.awt.Color(0, 51, 102));
        jLblAyuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblAyuda.setText("DGG - Daniel, Green y Golo.");
        jLblAyuda.setAutoscrolls(true);
        jLblAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLblAyuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/bios/dgg/bibliotecamistica/imagenes/biblioteca.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLblAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        this.salir();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSociosActionPerformed
        VentanaSocios ventana = new VentanaSocios(this); //Creo ventanaSocios y le paso el menu como parametro para poder volver al menu
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnSociosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.salir();
    }//GEN-LAST:event_formWindowClosing

    private void jBtnSociosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSociosMouseEntered
        this.jLblAyuda.setText(this.jBtnSocios.getToolTipText());
    }//GEN-LAST:event_jBtnSociosMouseEntered

    private void jBtnSociosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSociosMouseExited
        this.jLblAyuda.setText("DGG - Daniel, Green y Golo.");
    }//GEN-LAST:event_jBtnSociosMouseExited

    private void jBtnAutoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAutoresMouseExited
        this.jLblAyuda.setText("DGG - Daniel, Green y Golo.");
    }//GEN-LAST:event_jBtnAutoresMouseExited

    private void jBtnCategoriasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCategoriasMouseExited
        this.jLblAyuda.setText("DGG - Daniel, Green y Golo.");
    }//GEN-LAST:event_jBtnCategoriasMouseExited

    private void jBtnLibrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLibrosMouseExited
        this.jLblAyuda.setText("DGG - Daniel, Green y Golo.");
    }//GEN-LAST:event_jBtnLibrosMouseExited

    private void jBtnPrestamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnPrestamosMouseExited
        this.jLblAyuda.setText("DGG - Daniel, Green y Golo.");
    }//GEN-LAST:event_jBtnPrestamosMouseExited

    private void jBtnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSalirMouseExited
        this.jLblAyuda.setText("DGG - Daniel, Green y Golo.");
    }//GEN-LAST:event_jBtnSalirMouseExited

    private void jBtnAutoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAutoresMouseEntered
        this.jLblAyuda.setText(this.jBtnAutores.getToolTipText());
    }//GEN-LAST:event_jBtnAutoresMouseEntered

    private void jBtnCategoriasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCategoriasMouseEntered
        this.jLblAyuda.setText(this.jBtnCategorias.getToolTipText());
    }//GEN-LAST:event_jBtnCategoriasMouseEntered

    private void jBtnLibrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLibrosMouseEntered
        this.jLblAyuda.setText(this.jBtnLibros.getToolTipText());
    }//GEN-LAST:event_jBtnLibrosMouseEntered

    private void jBtnPrestamosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnPrestamosMouseEntered
        this.jLblAyuda.setText(this.jBtnPrestamos.getToolTipText());
    }//GEN-LAST:event_jBtnPrestamosMouseEntered

    private void jBtnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSalirMouseEntered
        this.jLblAyuda.setText(this.jBtnSalir.getToolTipText());
    }//GEN-LAST:event_jBtnSalirMouseEntered

    private void jBtnAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAutoresActionPerformed
        VentanaAutores ventana = new VentanaAutores(this); //Creo ventanaAutores y le paso el menu como parametro para poder volver al menu
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnAutoresActionPerformed

    private void jBtnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCategoriasActionPerformed
        VentanaCategorias ventana = new VentanaCategorias(this); //Creo ventanaCategorias y le paso el menu como parametro para poder volver al menu
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnCategoriasActionPerformed

    private void jBtnLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLibrosActionPerformed
        VentanaLibros ventana = new VentanaLibros(this); //Creo ventanaLibros y le paso el menu como parametro para poder volver al menu
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnLibrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAutores;
    private javax.swing.JButton jBtnCategorias;
    private javax.swing.JButton jBtnLibros;
    private javax.swing.JButton jBtnPrestamos;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JButton jBtnSocios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblAyuda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
